import io,re
p='src/commands.rs'; s=io.open(p,encoding='utf-8').read()
nl="\r\n" if "\r\n" in s else "\n"
DOC=r"(?:///[^\r\n]*[\r\n]+)*"
new_begin=('#[tauri::command]{n}pub fn drag_begin(app:AppHandle)->Result<(),String>{[n]    let state=app.state::<AppState>();[n]    state.dragging.store(true,Ordering::Relaxed);[n]    if let Some(w)=app.get_webview_window("detail"){{let _=w.hide();}}[n]    if let Ok(mut g)=state.detail_account.lock(){{*g=None;}}[n]    // Real system cursor: immune to the window moving under us and to per-monitor DPI math.[n]    let Some((px,py))=crate::window::get_cursor_screen_pos()else{{return Ok(())}};[n]    let pos=win_outer_position(&app)?;[n]    *state.drag_grab.lock().unwrap()=(px-pos.x,py-pos.y);[n]    Ok(())[n]}[n][n]').replace('[n]',nl)
new_move=('#[tauri::command]{n}pub fn drag_move(app:AppHandle)->Result<(),String>{[n]    let state=app.state::<AppState>();[n]    if !state.dragging.load(Ordering::Relaxed){{return Ok(())}}[n]    let Some((px,py))=crate::window::get_cursor_screen_pos()else{{return Ok(())}};[n]    let win=app.get_webview_window("main").ok_or("窗口不存在")?;[n]    let monitors=win.available_monitors().map_err(|e|e.to_string())?;[n]    let Some(m)=monitors.iter().find(|m|{{let a=m.work_area();px>=a.position.x&&px<a.position.x+a.size.width as i32&&py>=a.position.y&&py<a.position.y+a.size.height as i32}}).cloned()[n]        .or_else(||win.current_monitor().ok().flatten())[n]        .or_else(||win.primary_monitor().ok().flatten())else{{return Ok(())}};[n]    let (side,fx,fy)=classify_drag(&state,&m,px,py);[n]    if side=="free"{{[n]        let (gx,gy)=*state.drag_grab.lock().unwrap();[n]        // A docked preview may have resized the window: restore rail size for this monitor.[n]        let Ok(settings)=state.settings.try_lock().map(|s|s.clone())else{{return Ok(())}};[n]        let rect=crate::window::dock_rect(&settings,&m,"rail",(0.5,0.5));[n]        let _=win.set_size(tauri::PhysicalSize::new(rect.w,rect.h));[n]        let _=win.set_position(tauri::PhysicalPosition::new(px-gx,py-gy));[n]    }}else{{[n]        let Ok(settings)=state.settings.try_lock().map(|s|s.clone())else{{return Ok(())}};[n]        let rect=crate::window::dock_rect(&settings,&m,&side,(fx,fy));[n]        crate::window::place(&win,&rect);[n]    }}[n]    Ok(())[n]}}[n][n]').replace('[n]',nl)
new_end=('#[tauri::command]{n}pub async fn drag_end(app:AppHandle)->Result<(),String>{[n]    let state=app.state::<AppState>();[n]    if !state.dragging.swap(false,Ordering::Relaxed){{return Ok(())}}[n]    let Some((px,py))=crate::window::get_cursor_screen_pos()else{{return Ok(())}};[n]    let win=app.get_webview_window("main").ok_or("窗口不存在")?;[n]    let monitors=win.available_monitors().map_err(|e|e.to_string())?;[n]    let m=monitors.iter().find(|m|{{let a=m.work_area();px>=a.position.x&&px<a.position.x+a.size.width as i32&&py>=a.position.y&&py<a.position.y+a.size.height as i32}}).cloned()[n]        .or_else(||win.current_monitor().ok().flatten())[n]        .or_else(||win.primary_monitor().ok().flatten()).ok_or("无法确定显示器")?;[n]    let (side,fx,fy)=classify_drag(&state,&m,px,py);[n]    let area=m.work_area();[n]    let mut settings=state.settings.lock().await.clone();[n]    settings.dock_side=side.clone();[n]    settings.monitor_name=m.name().cloned();[n]    if side=="free"{{[n]        let pos=win.outer_position().map_err(|e|e.to_string())?;[n]        let x=(pos.x as f64-area.position.x as f64).clamp(0.0,(area.size.width as f64).max(1.0));[n]        let y=(pos.y as f64-area.position.y as f64).clamp(0.0,(area.size.height as f64).max(1.0));[n]        settings.free_x=(x/area.size.width as f64).clamp(0.0,1.0);[n]        settings.free_y=(y/area.size.height as f64).clamp(0.0,1.0);[n]    }}else{{[n]        settings.free_x=fx;settings.free_y=fy;[n]        crate::window::position(&app,&settings,"rail");[n]    }}[n]    crate::config::save_settings(&settings)?;[n]    *state.settings.lock().await=settings.clone();[n]    let _=app.emit("settings-updated",&settings);[n]    Ok(())[n]}}[n][n]').replace('[n]',nl)
helper='fn win_outer_position(app:&tauri::AppHandle)->Result<tauri::PhysicalPosition<i32>,String>{'+nl+'    let win=app.get_webview_window("main").ok_or("窗口不存在")?;'+nl+'    win.outer_position().map_err(|e|e.to_string())'+nl+'}'+nl
m1=re.search(r'#\[tauri::command\]'+nl+DOC+r'pub fn drag_begin.*?(?=#\[tauri::command\]'+nl+DOC+r'pub fn drag_move)',s,re.S)
m2=re.search(r'#\[tauri::command\]'+nl+DOC+r'pub fn drag_move.*?(?=#\[tauri::command\]'+nl+DOC+r'pub async fn drag_end)',s,re.S)
m3=re.search(r'#\[tauri::command\]'+nl+DOC+r'pub async fn drag_end.*?(?=#\[tauri::command\]'+nl+DOC+r'pub async fn drag_cancel)',s,re.S)
assert m1 and m2 and m3,(bool(m1),bool(m2),bool(m3))
s=s[:m1.start()]+new_begin+s[m1.end():]
m2=re.search(r'#\[tauri::command\]'+nl+DOC+r'pub fn drag_move.*?(?=#\[tauri::command\]'+nl+DOC+r'pub async fn drag_end)',s,re.S)
s=s[:m2.start()]+new_move+s[m2.end():]
m3=re.search(r'#\[tauri::command\]'+nl+DOC+r'pub async fn drag_end.*?(?=#\[tauri::command\]'+nl+DOC+r'pub async fn drag_cancel)',s,re.S)
s=s[:m3.start()]+new_end+s[m3.end():]
a='fn classify_drag('
b=helper+'fn classify_drag('
assert s.count(a)==1; s=s.replace(a,b)
io.open(p,'w',encoding='utf-8',newline='\n').write(s); print("rewritten ok")
