import {useRef,useState} from 'react';import {invoke} from '@tauri-apps/api/core';
interface Row{source:string;model:string;day:string;hour:string;input:number;output:number;cache_read:number;cache_write:number;partial:boolean}
interface Summary{rows:Row[];scanned_files:number;changed_files:number;skipped_files:number;days:number;partial:boolean;cost_estimate:number|null;notes:string[]}
export function TokenSpend(){
  const [days,setDays]=useState(7),[result,setResult]=useState<Summary|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[group,setGroup]=useState('day');
  // A scan can take seconds; a reply for a range the user has since left must be dropped.
  const request=useRef(0);
  const scan=async()=>{const seq=++request.current;setBusy(true);setError('');try{const summary=await invoke<Summary>('token_spend',{days});if(seq===request.current)setResult(summary)}catch(e){if(seq===request.current)setError(String(e))}finally{if(seq===request.current)setBusy(false)}};
  const rows=new Map<string,number[]>();for(const r of result?.rows||[]){const key=group==='model'?`${r.source} / ${r.model}`:group==='hour'?`${r.day} ${r.hour}`:r.day;const old=rows.get(key)||[0,0,0,0];rows.set(key,old.map((n,i)=>n+[r.input,r.output,r.cache_read,r.cache_write][i]));}
  return <section className="space-y-4"><h2 className="text-lg font-semibold">Token 消耗</h2><p>读取本机使用记录，统计范围包含今天。费用估算暂不可用。</p><div className="flex gap-3"><select className="bg-zinc-800 p-2 rounded disabled:opacity-40" disabled={busy} value={days} onChange={e=>{request.current++;setDays(Number(e.target.value));setResult(null)}}>{[7,30,90].map(d=><option key={d} value={d}>最近 {d} 天</option>)}</select><button disabled={busy} className="bg-emerald-700 px-3 rounded disabled:opacity-40" onClick={()=>void scan()}>{busy?'正在读取…':'读取使用记录'}</button><select className="bg-zinc-800 p-2 rounded" value={group} onChange={e=>setGroup(e.target.value)}><option value="day">按天</option><option value="hour">按小时</option><option value="model">按来源 / 模型</option></select></div>{busy&&<p className="text-xs text-zinc-500">首次读取需要解析本机全部近期记录，可能要十几秒到一分钟；切换页签不会丢失结果。</p>}{error&&<p className="text-amber-400">{error}</p>}
    {result&&<><p className="text-zinc-400">最近 {result.days} 天：检查 {result.scanned_files} 个文件，更新 {result.changed_files} 个，跳过 {result.skipped_files} 项。{result.partial?'统计不完整，请结合来源限制阅读。':''}</p>{result.notes.map((n,i)=><p key={i} className="text-xs text-zinc-500">{n}</p>)}<div className="overflow-auto"><table className="w-full text-xs text-right"><thead><tr>{['分组','输入','输出','缓存读取','缓存写入'].map(h=><th key={h} className="p-2 border-b border-zinc-700">{h}</th>)}</tr></thead><tbody>{[...rows].map(([label,counts])=><tr key={label}><td className="p-2 text-left">{label}</td>{counts.map((n,i)=><td key={i} className="p-2">{n.toLocaleString()}</td>)}</tr>)}</tbody></table></div>{!rows.size&&<p>此区间未找到可解析记录；不代表账号没有消耗。</p>}</>}
  </section>;
}
